InteriorDesign/InteriorDesign.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using InteriorDesign.Core.Services.Application.CartService;
using InteriorDesign.Core.ViewModels.ConfiguredProductViewModels;
using InteriorDesign.Web.Extensions;

namespace InteriorDesign.Web.Controllers
{
    [Authorize]
    public class CartController : BaseController
    {
        private readonly ICartService _service;
        private readonly ILogger _logger;

        public CartController(
            ICartService service,
            ILogger<CartController> logger)
        {
            _service = service;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                // Use this exception to test error handling:
                //throw new Exception("Test Exception");

                var products = await _service.GetAllProductsByUserIdAsync(User.Id());

                return View(products);
            }
            catch (Exception ex)
            {
                return RedirectToError(ex, _logger, nameof(CartController), nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditProduct(string productId)
        {
            try
            {
                // Use this exception to test error handling:
                //throw new Exception("Test Exception");

                var viewModel = await _service.GetProductByIdAsync(productId);

                return View(viewModel);
            }
            catch (Exception ex)
            {
                return RedirectToError(ex, _logger, nameof(CartController), nameof(EditProduct));
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditProduct(ConfiguredProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                // Use this exception to test error handling:
                //throw new Exception("Test Exception");

                await _service.EditAsync(model);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToError(ex, _logger, nameof(CartController), nameof(EditProduct));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string productId)
        {
            try
            {
                // Use this exception to test error handling:
                //throw new Exception("Test Exception");

                await _service.DeleteProductByIdAsync(productId);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToError(ex, _logger, nameof(CartController), nameof(Delete));
            }
        }
    }
}

InteriorDesign/InteriorDesign.Web/Controllers/OrdersController.cs
using InteriorDesign.Core.Services.Common.EmailSendService;
using InteriorDesign.Core.Services.Application.UserOrderService;
using InteriorDesign.Core.ViewModels.OrderViewModels;
using InteriorDesign.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InteriorDesign.Web.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly IUserOrderService _service;
        private readonly IAppEmailSender _emailSender;
        private readonly ILogger _logger;

        public OrdersController(
            IUserOrderService service, 
            IAppEmailSender emailSender,
            ILogger<OrdersController> logger)
        {
            _service = service;
            _emailSender = emailSender;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                // Use this exception to test error handling:
                //throw new Exception("Test Exception");

                var model = await _service.GetOrderInfoAsync(User.Id());

                return View(model);
            }
            catch (Exception ex)
            {
                return RedirectToError(ex, _logger, nameof(OrdersController), nameof(Index));
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrder(CreateOrderViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            model.UserId = User.Id();

            var price = String.Format("{0:0.00}", model.TotalPrice);
            var subject = "Your order confirmed";
            var body = $"<p>Email From: Interior Design</p><p>Dear {model.FirstName} {model.LastName},</p> <p>Thank you for your order.</p> <p>It will be shipped in 2 working days.</p> <p>Delivery address:</p> <p>{model.DeliveryAddress}</p> <p>Order total price: {price} Euro.</p> <p>Your order status: Confirmed.</p>";

            try
            {
                // Use this exception to test error handling:
                //throw new Exception("Test Exception");

                await _service.CreateOrderAsync(model);
                await _emailSender.SendAsync(subject, body, model.Email);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToError(ex, _logger, nameof(OrdersController), nameof(CreateOrder));
            }
        }
    }
}

InteriorDesign/InteriorDesign.Web/Views/Cart/EditProduct.cshtml
@using InteriorDesign.Infrastructure.Data.Models.DataBaseModels
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@model ConfiguredProductViewModel

@{
    ViewData["Title"] = "Product Details";
}

<div id="product-wrapper" class="wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-10">
                    <h1>@String.Concat(Model.TypeName + " " + Model.ProductName + " of category " + Model.CategoryName)</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <h3 class="d-inline-block d-sm-none">LOWA Men’s Renegade GTX Mid Hiking Boots Review</h3>
                        <div class="col-12">
                            <img src="@Model.ImageUrl" class="product-image" alt="@Model.ProductName">
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <h3 class="my-3">@Model.ProductName</h3>
                        <p style="margin: 0;">Product type: @Model.TypeName</p>
                        <p style="margin: 0;">Category: @Model.CategoryName</p>
                        <p style="margin: 0;">Color: @Model.ColorName</p>
                        <p style="margin: 0;">Single price: @String.Format("{0:0.00}", Model.SinglePrice).Replace(",", ".") <i class="fa fa-eur" aria-hidden="true"></i></p>

                        <hr>

                        <div class="bg-gray py-2 px-3 mt-4">
                            <h2 class="mb-0" style="margin: 0.5rem; text-align: center;" >
                                <span id="product-total">@String.Format("{0:0.00}", Model.SinglePrice * Model.Quantity).Replace(",", ".")</span> <i class="fa fa-eur" aria-hidden="true"></i>
                            </h2>
                            <h4 class="mt-0" style="text-align: center;">
                                <small>Excluding delivery</small>
                            </h4>
                        </div>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <form asp-controller="Cart" asp-action="EditProduct" class="mt-4" style="display: flex;" enctype="multipart/form-data">
                                <div>
                                    <label asp-for="Quantity" style="margin: 0;" />
                                    <input asp-for="Quantity"
                                       class="input-quantity"
                                       id="input-quantity"
                                       type="number"
                                       min="1"
                                       max="9"
                                       onchange="onChangeHandler()"
                                       value="@Model.Quantity" />
                                </div>

                                <input type="hidden" asp-for="@Model.ProductName" />
                                <input type="hidden" asp-for="@Model.ProductPrice" />
                                <input type="hidden" asp-for="@Model.CategoryName" />
                                <input type="hidden" asp-for="@Model.TypeName" />
                                <input type="hidden" asp-for="@Model.ModelName" />
                                <input type="hidden" asp-for="@Model.ColorName" />
                                <input type="hidden" asp-for="@Model.ImageUrl" />
                                <input type="hidden" asp-for="@Model.SinglePrice" />
                                <input type="hidden" asp-for="@Model.Id" />
                                <input type="hidden" asp-for="@Model.ProductId" />

                                <input type="submit"
                                   class="btn btn-success btn-lg btn-flat"
                                   onclick="return confirm('Are you sure you want to edit quantity of this product in your shopping cart?')"
                                   style="width: 30%;"
                                   value="Edit" />

                                <a asp-controller="Cart"
                                    asp-action="Index"
                                    class="btn btn-default btn-lg btn-flat"
                                    style="width: 30%; margin-inline: 0.5rem;"
                                    onclick="displayBusyIndicator()">
                                        Cancel
                                </a>

                                <a asp-controller="Cart" 
                                    asp-action="Delete" 
                                    asp-route-productId="@Model.Id"
                                    onclick="return confirm('Are you sure you want to delete this product from your shopping cart?')"
                                    class="btn btn-primary btn-lg btn-flat" 
                                    style="width: 30%;">
                                        Delete
                                </a>
                            </form>
                        }
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->

    <script type="text/javascript">
        var singlePrice = JSON.parse('@Json.Serialize(@Model.SinglePrice)');
        var quantity = '@Model.Quantity';

        const priceElement = document.getElementById('product-total');
        const quantityElement = document.getElementById('input-quantity');

        let currentQuantity = quantityElement.value;

        onChangeHandler = () => {
            currentQuantity = quantityElement.value;
            let currentPrice = currentQuantity * singlePrice;

            priceElement.value = currentPrice;
            priceElement.textContent = currentPrice.toFixed(2);
        }
    </script>
</div>

InteriorDesign/InteriorDesign.Web/Views/Cart/Index.cshtml
@using Microsoft.AspNetCore.Identity;

@model List<ConfiguredProductViewModel>

@{
    ViewData["Title"] = "Cart";
}

<div>
    @if (!Model.Any())
    {
        <div class="section-header wow fadeInUp" style="margin-top: 25vh;">
            <h2>Your Cart is empty!</h2>
        </div>
    }
    else
    {
        <div class="card wow fadeInUp" style="margin-bottom: 4rem;">
            <div class="card-header border-0">
                <h3 class="card-title" style="margin-left: 1rem; color: orangered;">Configured products in you cart:</h3>
                <div class="card-tools" style="display: flex; flex-direction: column;">
                    <a asp-controller="Orders"
                        asp-action="Index"
                        onclick="return confirm('Are you sure you want to order these products?')"
                        class="btn btn-primary btn-lg btn-flat"
                        style="width: 100%">
                            Make Order
                    </a>
                </div>
                <div class="card-tools" style="display: flex; flex-direction: column;">
                    <h3 class="card-title" style="margin-right: 3rem; color: darkorange;">configured products count: <strong>@Model.Count</strong></h3>
                    <h3 class="card-title" style="margin-right: 3rem; color: red;">total price: <strong>@String.Format("{0:0.00}", Model.Sum(x => x.ProductPrice)).Replace(",", ".")</strong> <i class="fa fa-eur" aria-hidden="true"></i></h3>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-striped table-valign-middle">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Category</th>
                            <th>Type</th>
                            <th>Model</th>
                            <th>Color</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model)
                        {
                            <partial name="_CartRowPartial" , model=product />
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
</div>